### ISSUE TITLE
GK-News-Show-Pro isn't resizing images

### ISSUE THREAD

**Issue by pattonmcginley** [GavickPro/GK-News-Show-Pro#37]
GK-News-Show-Pro isn't resizing feature images from posts. I'm using the Gavick News Theme. GK-News-Show-Pro is ignoring input for the image size from the back-end of the widget. It's resizing the images as squares based on the width of the "inset" column the widget is assigned to.

**Comment by piotrkunicki** [comment]
Hello,
Could you send an URL to your website with this issue visible?
Generally News Show Pro generates thumbnails from the image size from the widget settings, but News Theme is responsive, so images width is adjusted to the container.

**Comment by pattonmcginley** [comment]
The URL is http://dev.masonrymagazine.com. Is there a way to adjust override the responsive re-sizing?

**Comment by piotrkunicki** [comment]
Yes, it's possible but first try to change image size in you widget settings, set image size to 300 x 200px for example and the check the effect, because now the images are generated from 100x100px dimensions.

BTW you are using GavickPro News theme, so please create new thread on the forum in the News WP category: https://www.gavick.com/forums/news-wp
I'll be able to help you faster.

**Comment by pattonmcginley** [comment]
Sorry, I saw an earlier post re. NSP on the Gavick forum and the poster was told to post here.

For some reason the resize is now working. Thanks.
